adventureworks:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 10.0.0.187
      port: 5432
      user: root
      pass: pickleJuice123!@#
      dbname: dbt_dim_model_dev
      schema: adventureworks_dim_model
      threads: 4

